version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fooddb
      MYSQL_USER: fooduser
      MYSQL_PASSWORD: foodpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: fooduser
      DB_PASSWORD: foodpass
      DB_NAME: fooddb
    command: node server.js

volumes:
  db_data:
