name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files to EC2 using SCP
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ubuntu/food-app"

    - name: SSH into EC2 and run app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        # script: |
        #   cd /home/ubuntu/food-app
        #   docker build -t foodapp .
        #   docker stop foodapp-container || true
        #   docker rm foodapp-container || true
        #   docker run -d -p 3000:3000 --name foodapp-container foodapp
        
        script: |
           cd /home/ubuntu/food-app
           docker-compose down || true
           docker-compose build
           docker-compose up -d

